from videos.tests.celery_tasks import *
from videos.tests.downloads import *
from videos.tests.feeds import *
from videos.tests.following import *
from videos.tests.forms import *
from videos.tests.metadata import *
from videos.tests.models import *
from videos.tests.rpc import *
from videos.tests.template_tags import *
from videos.tests.uploads import *
from videos.tests.video_types import *
from videos.tests.views import *
from videos.tests.importer import *
