from apps.videos.tests.celery_tasks import *
from apps.videos.tests.downloads import *
from apps.videos.tests.feeds import *
from apps.videos.tests.following import *
from apps.videos.tests.forms import *
from apps.videos.tests.metadata import *
from apps.videos.tests.models import *
from apps.videos.tests.rpc import *
from apps.videos.tests.template_tags import *
from apps.videos.tests.uploads import *
from apps.videos.tests.video_types import *
from apps.videos.tests.video_urls import *
from apps.videos.tests.views import *
